ARDUINO_LIBRARIES := ArduinoJson6 DHTesp

SPIFF_SIZE		?= 196608

ENABLE_ESPCONN = 1

COMPONENT_VARS += ENABLE_EXPERIMENTAL_RL_CONTROLLER
ENABLE_EXPERIMENTAL_RL_CONTROLLER ?= 0
ifeq ($(ENABLE_EXPERIMENTAL_RL_CONTROLLER),1)
COMPONENT_CXXFLAGS += -DFERMENTBOX_EXPERIMENTAL_RL_CONTROLLER=1
endif
