name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clone_sming
      run: git clone https://github.com/SmingHub/Sming.git
    - name: Build Sming
      run: |
        sudo Sming/Tools/install.sh host
        . Sming/Tools/export.sh
    - name: make
      run: |
        export SMING_HOME=$PWD/Sming
        cd fermentbox-backend 
        make -j4 SMING_ARCH=Host

